server:
  port: 8081

spring:
  redis:
    host: 39.97.233.123
    port: 6379
    database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.233.123:3306/wwt?autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.springdata
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java