server:
  port: 8081

spring:
  redis:
    sentinel:
      master: kfcredis
      nodes: memberredis1kfc.lexue.inc:26379,memberredis2kfc.lexue.inc:26379,memberredis3kfc.lexue.inc:26379
    database: 1
    password: lexue_kfc
    lettuce:
      pool:
        min-idle: 5
        max-idle: 50
        max-active: 100
        max-wait: 1000

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.springdata
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java